# Simple workflow for deploying static content to GitHub Pages
name: Playground

on:
  # Runs on pushes playground folder
  # push:
  #  branches: ["main"]
  #  paths:
  #    - '/playground/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and Build - Codeverter # temporal until npm package were uploaded.
        run: |
          npm ci
          npm run build:prod
      - name: Install and Build - Playground
        run: |
          npm ci
          CI=false
          PUBLIC_URL=https://southworks.github.io/codeverter npm run build
        working-directory: ./playground
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './playground/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
